import XCTest
@testable import CoreModels

/// Tests for the extended `PlaybackHistoryEntry` model.
///
/// Validates backward compatibility with existing callers, new optional fields,
/// Codable round-trip, and Identifiable conformance.
final class PlaybackHistoryEntryTests: XCTestCase {

    // MARK: - Backward Compatibility

    func testInitWithOriginalFieldsOnly() {
        let entry = PlaybackHistoryEntry(
            episodeId: "ep-1",
            podcastId: "pod-1",
            duration: 1800,
            completed: true
        )
        XCTAssertEqual(entry.episodeId, "ep-1")
        XCTAssertEqual(entry.podcastId, "pod-1")
        XCTAssertEqual(entry.duration, 1800)
        XCTAssertTrue(entry.completed)
        XCTAssertNil(entry.episodeTitle)
        XCTAssertNil(entry.podcastTitle)
        XCTAssertNil(entry.playbackSpeed)
    }

    // MARK: - Extended Fields

    func testInitWithAllFields() {
        let entry = PlaybackHistoryEntry(
            episodeId: "ep-1",
            podcastId: "pod-1",
            duration: 3600,
            completed: true,
            episodeTitle: "Great Episode",
            podcastTitle: "Best Podcast",
            playbackSpeed: 1.5
        )
        XCTAssertEqual(entry.episodeTitle, "Great Episode")
        XCTAssertEqual(entry.podcastTitle, "Best Podcast")
        XCTAssertEqual(entry.playbackSpeed, 1.5)
    }

    // MARK: - Codable Round-trip

    func testCodableRoundTripWithAllFields() throws {
        let original = PlaybackHistoryEntry(
            id: "test-id",
            episodeId: "ep-1",
            podcastId: "pod-1",
            playedAt: Date(timeIntervalSince1970: 1700000000),
            duration: 2400,
            completed: true,
            episodeTitle: "Test Episode",
            podcastTitle: "Test Podcast",
            playbackSpeed: 2.0
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(PlaybackHistoryEntry.self, from: data)

        XCTAssertEqual(decoded.id, original.id)
        XCTAssertEqual(decoded.episodeId, original.episodeId)
        XCTAssertEqual(decoded.podcastId, original.podcastId)
        XCTAssertEqual(decoded.duration, original.duration)
        XCTAssertEqual(decoded.completed, original.completed)
        XCTAssertEqual(decoded.episodeTitle, original.episodeTitle)
        XCTAssertEqual(decoded.podcastTitle, original.podcastTitle)
        XCTAssertEqual(decoded.playbackSpeed, original.playbackSpeed)
    }

    func testCodableRoundTripWithNilOptionals() throws {
        let original = PlaybackHistoryEntry(
            episodeId: "ep-1",
            podcastId: "pod-1",
            duration: 1800,
            completed: false
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(PlaybackHistoryEntry.self, from: data)

        XCTAssertEqual(decoded.episodeId, original.episodeId)
        XCTAssertNil(decoded.episodeTitle)
        XCTAssertNil(decoded.podcastTitle)
        XCTAssertNil(decoded.playbackSpeed)
    }

    func testDecodingLegacyJSONWithoutNewFields() throws {
        // Simulate JSON from before the extension — no episodeTitle/podcastTitle/playbackSpeed keys
        let legacyJSON = """
        {
            "id": "legacy-1",
            "episodeId": "ep-1",
            "podcastId": "pod-1",
            "playedAt": 1700000000,
            "duration": 1800,
            "completed": true
        }
        """.data(using: .utf8)!

        let decoded = try JSONDecoder().decode(PlaybackHistoryEntry.self, from: legacyJSON)
        XCTAssertEqual(decoded.id, "legacy-1")
        XCTAssertEqual(decoded.episodeId, "ep-1")
        XCTAssertNil(decoded.episodeTitle)
        XCTAssertNil(decoded.podcastTitle)
        XCTAssertNil(decoded.playbackSpeed)
    }

    // MARK: - Identifiable

    func testIdentifiableConformance() {
        let entry = PlaybackHistoryEntry(
            id: "unique-id",
            episodeId: "ep-1",
            podcastId: "pod-1",
            duration: 300,
            completed: false
        )
        // Identifiable requires an `id` property
        XCTAssertEqual(entry.id, "unique-id")
    }

    func testAutoGeneratedId() {
        let entry1 = PlaybackHistoryEntry(
            episodeId: "ep-1",
            podcastId: "pod-1",
            duration: 300,
            completed: false
        )
        let entry2 = PlaybackHistoryEntry(
            episodeId: "ep-1",
            podcastId: "pod-1",
            duration: 300,
            completed: false
        )
        // Each entry gets a unique auto-generated ID
        XCTAssertNotEqual(entry1.id, entry2.id)
    }

    // MARK: - Equatable

    func testEqualityWithSameFields() {
        let date = Date(timeIntervalSince1970: 1700000000)
        let a = PlaybackHistoryEntry(
            id: "same-id",
            episodeId: "ep-1",
            podcastId: "pod-1",
            playedAt: date,
            duration: 1800,
            completed: true,
            episodeTitle: "Test",
            podcastTitle: "Podcast",
            playbackSpeed: 1.0
        )
        let b = PlaybackHistoryEntry(
            id: "same-id",
            episodeId: "ep-1",
            podcastId: "pod-1",
            playedAt: date,
            duration: 1800,
            completed: true,
            episodeTitle: "Test",
            podcastTitle: "Podcast",
            playbackSpeed: 1.0
        )
        XCTAssertEqual(a, b)
    }
}
